### PR TITLE
 Removed old code, converted butt lifter to PID, commented code

### PR DESCRIPTION
**Pull request by PseudoResonance**
All old code that is now replaced has been removed
Butt lifter was converted to PID based control, exactly like the
elevator - needs tuning
Comments throughout elevator and butt lifter subsystems to make easier
to understand
Renamed methods and variables for consistency and conciseness

### CODE REVIEW

**Comment by manpreet-singh** [comment]
Just curious, were all of these changes tested before being committed?

**Comment by nhl01** [comment]
We didn't have the robot out of the bag on Monday, but the code compiles without any problems. We will try to test at the pit today if we can.

**Comment by manpreet-singh** [comment]
Good luck. Drive it like you stole it.

**Comment by nhl01** [comment]
Thank you!

**Pull request merged**
